### ISSUE TITLE
missing `arm64_runner.s`?

### ISSUE THREAD

**Issue by dlevi309** [SongXiaoXi/Reductant#1]
Hey, really fascinating work you’ve done 👍 I just wanted to ask, did you intentionally leave [arm64_runner.s](https://github.com/SongXiaoXi/Reductant/blob/master/arm64_runner.s) blank or was it a mistake?

**Comment by SongXiaoXi** [comment]
Well, if I remember correctly, I just want to create a minimal arm64 executable using an empty arm64_runner.s, forcing the kernel to create an arm64 process without PAC. Then, directly and forcibly load an unmodified arm64e executable on an arm64 device.

**Comment by dlevi309** [comment]
ah, that makes sense! thanks for answering so quickly
